import { useEffect, useState, useCallback, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Zap, Wifi, CheckCircle2, AlertCircle, ShieldCheck } from 'lucide-react';
import { useWallet } from '../context/WalletContext.js';
import { useClaim } from '../hooks/useClaim.js';
import { Button } from '../components/ui/Button.js';
import { HashChip } from '../components/ui/HashChip.js';
import { CopyButton } from '../components/ui/CopyButton.js';

interface ClaimState {
  params: any | null;
  nullifier: string | null;
  txHash: string | null;
  done: boolean;
}

export function Claim() {
  const { isConnected, connect, isConnecting, client } = useWallet();

  const auditorPublicKey = useMemo(() => {
    try {
      const stored = localStorage.getItem('tesseract-audit-key');
      if (stored) return (JSON.parse(stored) as { publicKey: string }).publicKey;
    } catch { /* ignore */ }
    return undefined;
  }, []);

  const { parseCurrentUrl, claim, isLoading, error, clearError } = useClaim(client, auditorPublicKey);

  const [state, setState] = useState<ClaimState>({ params: null, nullifier: null, txHash: null, done: false });
  const [fetchingProof, setFetchingProof] = useState(false);

  useEffect(() => {
    const params = parseCurrentUrl();
    setState(s => ({ ...s, params }));
  }, [parseCurrentUrl]);

  const handleClaim = useCallback(async () => {
    if (!state.params) return;
    clearError();
    setFetchingProof(true);
    try {
      const result = await claim(state.params);
      setState(s => ({ ...s, nullifier: result.nullifier, txHash: result.txHash, done: true }));
    } finally {
      setFetchingProof(false);
    }
  }, [state.params, claim, clearError]);

  // No URL params
  if (!state.params) {
    return (
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="flex flex-col items-center justify-center min-h-[60vh] px-6 relative w-full max-w-lg mx-auto">
        <div className="absolute top-0 w-64 h-64 bg-[var(--accent)] opacity-5 rounded-full blur-[100px] pointer-events-none" />
        
        <div className="doppelrand-shell w-full group relative">
          <div className="absolute -inset-8 bg-[var(--accent)] opacity-0 group-hover:opacity-5 rounded-full blur-[40px] pointer-events-none transition-opacity duration-700" />
          <div className="doppelrand-core text-center !p-12 relative overflow-hidden">
            <div className="w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-8 bg-[rgba(255,255,255,0.02)] border border-[rgba(255,255,255,0.05)] shadow-[inset_0_1px_0_rgba(255,255,255,0.05)]">
              <Zap size={32} className="text-[var(--muted)] opacity-50" />
            </div>
            <h2 className="text-2xl font-bold tracking-tight mb-4 text-white">Awaiting Claim Data</h2>
            <p className="text-sm leading-relaxed mb-8 text-[var(--muted)] max-w-[260px] mx-auto">
              You haven't provided a valid claim URL. Open a secure link generated by a payer to initiate the zero-knowledge claim process.
            </p>
            <div className="p-4 rounded-xl text-xs font-mono bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.05)] text-[var(--muted)] text-left">
              Example:<br />
              <span className="opacity-50">/app/claim?batchId=…&amount=…</span>
            </div>
          </div>
        </div>
      </motion.div>
    );
  }

  // Success
  if (state.done && state.nullifier) {
    return (
      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="max-w-lg mx-auto py-12">
        <div className="flex flex-col items-center text-center mb-10 relative">
          <div className="absolute top-0 w-64 h-64 bg-[var(--success)] opacity-10 rounded-full blur-[100px] pointer-events-none" />
          <div className="w-20 h-20 rounded-full bg-[rgba(16,185,129,0.1)] border border-[rgba(16,185,129,0.2)] flex items-center justify-center mb-6 shadow-[0_0_30px_rgba(16,185,129,0.2)]">
            <CheckCircle2 size={32} className="text-[var(--success)]" />
          </div>
          <h1 className="text-4xl font-bold tracking-tighter text-white mb-4">Payment Claimed</h1>
          <div className="px-5 py-2 rounded-full border border-[rgba(255,255,255,0.1)] bg-[rgba(255,255,255,0.03)] text-sm font-mono text-[var(--muted)]">
            TX <span className="text-white">{state.txHash?.slice(0, 16)}…{state.txHash?.slice(-16)}</span>
          </div>
        </div>

        <div className="doppelrand-shell mb-8">
          <div className="doppelrand-core !p-8 text-center bg-[rgba(0,0,0,0.2)] border-b border-[rgba(255,255,255,0.05)] rounded-b-none">
            <p className="text-[10px] font-bold tracking-[0.2em] uppercase mb-4 text-[var(--success)]">Verified Payload Amount</p>
            <div className="flex items-baseline justify-center gap-3">
              <span className="font-mono text-6xl font-bold text-white tracking-tighter">{state.params.amount.toString()}</span>
              <span className="text-xl font-medium text-[var(--success)]">NIGHT</span>
            </div>
          </div>
          <div className="doppelrand-core !p-6 bg-[var(--surface-hi)] rounded-t-none">
            <p className="text-[10px] font-bold tracking-[0.2em] uppercase mb-4 text-[var(--muted)] flex items-center gap-2">
              <ShieldCheck size={14} className="text-[var(--accent)]" /> Cryptographic Nullifier
            </p>
            <div className="flex items-center gap-4 p-4 rounded-xl bg-[rgba(0,0,0,0.4)] border border-[rgba(255,255,255,0.05)] mb-3">
              <span className="font-mono text-xs flex-1 break-all text-[var(--muted)] leading-relaxed">
                {state.nullifier}
              </span>
              <CopyButton text={state.nullifier} size="sm" className="opacity-70 hover:opacity-100" />
            </div>
            <p className="text-[10px] text-[var(--muted)] uppercase tracking-widest pl-1">Keep this hash to prove your claim.</p>
          </div>
        </div>
      </motion.div>
    );
  }

  // Wallet not connected
  if (!isConnected) {
    return (
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="flex flex-col items-center justify-center min-h-[60vh] px-6 relative w-full max-w-lg mx-auto">
        <div className="absolute top-0 w-64 h-64 bg-[var(--accent)] opacity-10 rounded-full blur-[100px] pointer-events-none" />
        
        <div className="doppelrand-shell w-full group relative">
          <div className="absolute -inset-8 bg-[var(--accent)] opacity-0 group-hover:opacity-10 rounded-full blur-[50px] pointer-events-none transition-opacity duration-700" />
          <div className="doppelrand-core text-center !p-12 relative overflow-hidden">
            <p className="text-[10px] font-bold tracking-[0.2em] uppercase mb-4 text-[var(--muted)]">Pending Transfer</p>
            <div className="flex items-baseline justify-center gap-3 mb-10">
              <span className="font-mono text-7xl font-bold text-white tracking-tighter">{state.params.amount.toString()}</span>
              <span className="text-2xl font-medium text-[var(--accent)]">NIGHT</span>
            </div>
            
            <div className="h-px w-full bg-gradient-to-r from-transparent via-[rgba(255,255,255,0.1)] to-transparent mb-10" />
            
            <p className="text-sm mb-8 leading-relaxed text-[var(--muted)] max-w-xs mx-auto">
              A secure payload is waiting. Connect your 1AM wallet to generate a ZK proof and claim the funds.
            </p>
            
            <div className="relative group/btn w-full">
              <div className="absolute -inset-[2px] bg-gradient-to-r from-[var(--accent)] to-purple-600 rounded-2xl opacity-50 group-hover/btn:opacity-100 blur-sm transition-opacity duration-300"></div>
              <Button variant="primary" size="lg" magnetic isLoading={isConnecting} onClick={connect} className="relative w-full justify-center bg-[var(--surface-hi)] border-none text-white hover:bg-[var(--surface-hi)] px-8 py-4 rounded-xl gap-3 shadow-none">
                <Wifi size={16} />
                {isConnecting ? 'Connecting…' : 'Connect 1AM Wallet'}
              </Button>
            </div>
          </div>
        </div>
      </motion.div>
    );
  }

  // Ready to claim
  return (
    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="max-w-lg mx-auto py-10">
      <div className="flex items-center gap-3 mb-10 relative z-10">
        <div className="p-2 rounded-xl bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.05)]">
          <Zap size={20} className="text-[var(--accent)]" />
        </div>
        <h1 className="text-3xl font-bold tracking-tight text-white">Execute Claim</h1>
      </div>

      <div className="doppelrand-shell mb-8 relative group">
        <div className="absolute -inset-8 bg-[var(--accent)] opacity-5 rounded-full blur-[60px] pointer-events-none group-hover:opacity-10 transition-opacity duration-700" />
        <div className="doppelrand-core !p-8 relative overflow-hidden bg-[rgba(0,0,0,0.4)]">
          <p className="text-[10px] font-bold tracking-[0.2em] uppercase mb-4 text-[var(--muted)]">Authorized Transfer</p>
          <div className="flex items-baseline gap-3 mb-10">
            <span className="font-mono text-7xl font-bold text-white tracking-tighter">{state.params.amount.toString()}</span>
            <span className="text-xl font-medium text-[var(--accent)]">NIGHT</span>
          </div>

          <div className="space-y-4 border-t border-[rgba(255,255,255,0.05)] pt-6">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-widest text-[var(--muted)]">Source Batch</span>
              <HashChip hash={state.params.batchId} className="text-white bg-[rgba(255,255,255,0.05)]" />
            </div>
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-widest text-[var(--muted)]">Merkle Index</span>
              <span className="text-sm font-mono text-white bg-[rgba(255,255,255,0.05)] border border-[rgba(255,255,255,0.1)] px-3 py-1 rounded-lg">#{state.params.leafIndex}</span>
            </div>
          </div>
        </div>
      </div>

      <AnimatePresence>
        {error && (
          <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} className="overflow-hidden mb-8">
            <div className="flex items-start gap-3 p-4 rounded-xl border border-[rgba(239,68,68,0.2)] bg-[rgba(239,68,68,0.1)] text-sm text-[var(--error)]">
              <AlertCircle size={16} className="shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="relative group/btn w-full">
        <div className="absolute -inset-[2px] bg-gradient-to-r from-[var(--accent)] to-purple-600 rounded-full opacity-50 group-hover/btn:opacity-100 blur-md transition-opacity duration-300"></div>
        <Button variant="primary" size="lg" magnetic isLoading={isLoading || fetchingProof} onClick={handleClaim} className="relative w-full justify-center bg-[#02000A] border border-[rgba(255,255,255,0.1)] text-white hover:bg-[var(--surface-hi)] px-8 py-4 rounded-full gap-3 shadow-none text-sm uppercase tracking-widest transition-all duration-300">
          <Zap size={16} className={fetchingProof ? 'animate-pulse' : ''} />
          {fetchingProof ? 'Synthesizing ZK Proof…' : 'Execute Private Claim'}
        </Button>
      </div>
    </motion.div>
  );
}
